package team.kavach.kanak.Weather

data class Current(
    val cloud: Int,
    val condition: Condition,
    val dewpoint_c: Float,
    val dewpoint_f: Float,
    val feelslike_c: Float,
    val feelslike_f: Float,
    val gust_kph: Float,
    val gust_mph: Float,
    val heatindex_c: Float,
    val heatindex_f: Float,
    val humidity: Int,
    val is_day: Int,
    val last_updated: String,
    val last_updated_epoch: Int,
    val precip_in: Int,
    val precip_mm: Int,
    val pressure_in: Float,
    val pressure_mb: Int,
    val temp_c: Float,
    val temp_f: Float,
    val uv: Float,
    val vis_km: Float,
    val vis_miles: Int,
    val wind_degree: Int,
    val wind_dir: String,
    val wind_kph: Float,
    val wind_mph: Float,
    val windchill_c: Float,
    val windchill_f: Float
)